---
title: "LiteartureReviewScript_Adhikari2022"
author: "Biraj Adhikari"
date: "2023-04-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

requirements
```{r}
library(networkD3) #for sankey Diagrams
library(dplyr)
library(ggplot2)
library(tidyr) #for the separate_rows function
library(ggpubr) #to combine multiple ggplot objects
```

```{r reading data}
data = read.csv('ForFig3_ResearchTrends_Methods.csv', header = TRUE, sep = ",")
```  

Making adjustments for the figures
```{r}
researchtrends <- data %>%
  group_by(Year) %>% summarize(n = n()) 
researchtrends$cumsum <- cumsum(researchtrends$n)

pies <- data %>% mutate(time.period = case_when(
  Year < 2008 ~ "First",
  Year >= 2008 & Year < 2015 ~ "Second",
  Year >=2015 & Year < 2018 ~ "Third",
  TRUE ~ "Fourth"
))
pies$time.period <- factor(pies$time.period, levels = c("First", "Second", "Third", "Fourth"))


pies <- pies %>% separate_rows(Method, sep = ", ") %>%
  group_by(time.period, Method) %>% summarize(Count = n())
pies$Method = factor(pies$Method, levels = c("Biophysical", "Monetary", "Socio-cultural"))

```

Creating a temporal trends in research figure
```{r}
researchtrends_fig = ggplot(data = researchtrends, aes(x = Year, y = n)) + 
  
  #bar chart for publications per year
  geom_bar(color = "#608000", fill = "#608000", stat = "identity") + 
  
  #line/point plots for cumulative publications
  geom_line(aes(x = Year, y = cumsum/5, group = 1), size = 1,  color = "#ff9900") + 
  geom_point(aes(x = Year, y = cumsum/5), color = "#e68a00") + 
  
  #vertical lines indicating divides using natural Jenks
  geom_vline(xintercept = c(1994.5, 2007.5, 2014.5, 2017.5, 2020.5), 
             linetype = 2) + 
  
  #adjustments in axes
  labs( x = "Year") + 
  scale_x_continuous(breaks = seq(1995, 2020, 2), limits = c(1994.5, 2020.5)) + 
  scale_y_continuous("Number of publications", sec.axis = sec_axis(~. * 5, name = "Cumulative Publications")) + 
 
  #adjustment in theme
   theme(axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust=1), 
         legend.position = "bottom",
         panel.background = element_rect(fill = "white"),
         panel.grid.major = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"),
         panel.grid.minor = element_line(size = 0.15, linetype = "solid", colour = "#F0F0F0"))

researchtrends_fig
```  

Creating the pie charts for methods
```{r}
#1st Pie chart
pie1_fig = pies %>% filter(time.period == "First") %>% 
ggplot(aes(x = "", y = Count, fill = Method)) +
  geom_bar(stat = "identity", width = 1) + 
  scale_fill_manual(values = c("#b2df8a", "#1f78b4", "#a6cee3")) + 
    #geom_text(aes(label = paste(round(Count / sum(Count) * 100, 1), "%")),
           # position = position_stack(vjust = 0.5), size = 2.5) +
  labs(title = "1995-2007") + 
  
  coord_polar("y", start = 0) + 
  
  theme_void() +
  theme(legend.position = "none", 
        
        plot.title = element_text(hjust = 0.5, vjust = -3.5, size = 10))

pie1_fig


#2nd Pie Chart
pie2_fig = pies %>% filter(time.period == "Second") %>% 
ggplot(aes(x = "", y = Count, fill = Method)) +
  geom_bar(stat = "identity", width = 1) + 
  scale_fill_manual(values = c("#b2df8a", "#1f78b4", "#a6cee3")) + 
    #geom_text(aes(label = paste(round(Count / sum(Count) * 100, 1), "%")),
           # position = position_stack(vjust = 0.5), size = 2.5) +
  labs(title = "2007-2014") + 
  
  coord_polar("y", start = 0) + 
  
  theme_void() +
  theme(legend.position = "none", 
        
        plot.title = element_text(hjust = 0.5, vjust = -3.5, size = 10))

pie2_fig

#3rd Pie Chart
pie3_fig = pies %>% filter(time.period == "Third") %>% 
ggplot(aes(x = "", y = Count, fill = Method)) +
  geom_bar(stat = "identity", width = 1) + 
  scale_fill_manual(values = c("#b2df8a", "#1f78b4", "#a6cee3")) + 
    #geom_text(aes(label = paste(round(Count / sum(Count) * 100, 1), "%")),
           # position = position_stack(vjust = 0.5), size = 2.5) +
  labs(title = "2015-2017") + 
  
  coord_polar("y", start = 0) + 
  
  theme_void() +
  theme(legend.position = "none", 
        
        plot.title = element_text(hjust = 0.5, vjust = -3.5, size = 10))

pie3_fig

#4th Pie Chart
pie4_fig = pies %>% filter(time.period == "Fourth") %>% 
ggplot(aes(x = "", y = Count, fill = Method)) +
  geom_bar(stat = "identity", width = 1) + 
  scale_fill_manual(values = c("#b2df8a", "#1f78b4", "#a6cee3")) + 
    #geom_text(aes(label = paste(round(Count / sum(Count) * 100, 1), "%")),
           # position = position_stack(vjust = 0.5), size = 2.5) +
  labs(title = "2018-2020") + 
  
  coord_polar("y", start = 0) + 
  
  theme_void() +
  theme(legend.position = "none", 
        
        plot.title = element_text(hjust = 0.5, vjust = -3.5, size = 10))

pie4_fig
```  
Combining figures using facet grid

```{r}
png(filename = "Figure3.png",            
  width = 2400,        
  height = 2100,
  res = 300,  
  
  ) 

ggarrange(ggarrange(pie1_fig, pie2_fig, pie3_fig, pie4_fig, nrow = 1, ncol = 4, widths = c(1.3,0.8,0.5,0.5),  common.legend = TRUE, legend = "top"), researchtrends_fig, nrow = 2, ncol =1, heights = c(1, 3))

dev.off()
```

